# Standardkonfiguration för Web Scraping Toolkit

scraper:
  # HTTP-inställningar
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  timeout: 30
  connect_timeout: 10
  max_retries: 3
  delay_between_requests: 1.0
  
  # JavaScript-rendering
  use_playwright: false
  headless: true
  
  # Headers
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.5"
    Accept-Encoding: "gzip, deflate"
    Connection: "keep-alive"
    Upgrade-Insecure-Requests: "1"

rate_limiting:
  # Rate limiting-inställningar
  requests_per_minute: 60
  max_concurrent: 10
  delay_between_requests: 1.0
  
  # Burst-hantering
  burst_size: 5
  burst_window: 10

logging:
  # Loggningsinställningar
  level: "INFO"
  format: "json"
  file: "logs/scraper.log"
  
  # Loggrotation
  max_size: "10MB"
  backup_count: 5

export:
  # Export-inställningar
  default_format: "json"
  output_dir: "data"
  
  # Export-alternativ
  include_metadata: true
  flatten_nested: true
  timestamp_files: true

proxy:
  # Proxy-inställningar
  enabled: false
  url: null
  username: null
  password: null
  
  # Proxy-rotation
  rotation_enabled: false
  proxy_list: []

robots:
  # Robots.txt-hantering
  respect_robots: true
  robots_cache_time: 3600  # 1 timme

validation:
  # Valideringsinställningar
  validate_data: true
  strict_mode: false
  
  # Fältvalidering
  required_fields: []
  optional_fields: []
  
  # Datavalidering
  min_text_length: 1
  max_text_length: 10000

# Användaragent-rotation
user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15"

# Felhantering
error_handling:
  # Retry-logik
  retry_on_failure: true
  max_retries: 3
  retry_delay: 5.0
  exponential_backoff: true
  
  # Felkategorier
  retryable_errors:
    - "ConnectionError"
    - "TimeoutError"
    - "HTTPError"
  
  # Ignorera fel
  ignore_errors: []
